version: '3'
services:

  elasticsearch:
    hostname: elasticsearch-host
    container_name: elasticsearch-host
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.3
    volumes:
      - ${PWD}/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    networks:
      - net1

  kibana:
    hostname: kibana-host
    container_name: kibana-host
    build:
      context: .
      dockerfile: kibana-dockerfile
    links:
      - elasticsearch
    volumes:
      - ${PWD}/kibana.yml:/etc/kibana/kibana.yml
      - ${PWD}/logtrail.json:/usr/share/kibana/plugins/logtrail/logtrail.json
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - net1


  logstash:
    hostname: logstash-host
    container_name: logstash-host
    image: docker.elastic.co/logstash/logstash-oss:6.1.3
    links:
      - elasticsearch
    volumes:
      - ${PWD}/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "9125:9125/udp"
    depends_on:
      - elasticsearch
    networks:
      - net1

  accounts:
    environment: 
      - NODE_NAME=accounts
      - RELX_REPLACE_OS_VARS=true
      - DEBUG=1
    hostname: accounts-host
    container_name: accounts-host
    build: ../accounts/erlbank
    command: ["deploy-with-elk"]
    ports:
      - 8000:8000
    depends_on:
      - logstash
    networks:
      - net1

  transactions:
    environment: 
      - NODE_NAME=transactions
      - RELX_REPLACE_OS_VARS=true
      - ACCOUNT_NODE=accounts@accounts-host
    hostname: transactions-host
    container_name: transactions-host
    command: ["deploy-with-elk"]
    build: ../transactions/
    depends_on:
      - accounts
    networks:
      - net1

  bank_statements:
    environment: 
      - NODE_NAME=bankstatements
      - RELX_REPLACE_OS_VARS=true
      - ACCOUNT_NODE=accounts@accounts-host
      - TRANSACTION_NODE=transactions@transactions-host
    hostname: bankstatements-host
    container_name: bankstatements-host
    command: ["deploy-with-elk"]
    build: ../bank-statements/
    depends_on:
      - transactions
    networks:
      - net1

        
  nginx:
    environment: 
      - ACCOUNTS_HOST=accounts-host
      - TRANSACTIONS_HOST=transactions-host
      - BANK_STATEMENTS_HOST=bankstatements-host
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ../nginx/:/usr/share/nginx/
      - ../nginx/sites-enabled/:/etc/nginx/conf.d/
    ports:
      - 8080:80
      - 443:443
    depends_on:
      - bank_statements
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    networks:
      - net1

networks:
  net1:
    driver: bridge
